const significantList = {
    'numbers': [ 
        "zéro",
        "un",
        "deux",
        "trois",
        "quatre",
        "cinq",
        "six",
        "sept",
        "huit",
        "neuf",
        "dix",
        "onze",
        "douze",
        "treize",
        "quatorze",
        "quinze",
        "seize",
        "dix-sept",
        "dix-huit",
        "dix-neuf",
        "vingt",
        "vingt et un",
        "vingt-deux",
        "vingt-trois",
        "vingt-quatre",
        "vingt-cinq",
        "vingt-six",
        "vingt-sept",
        "vingt-huit",
        "vingt-neuf",
        "trente",
        "trente et un",
        "trente-deux",
        "trente-trois",
        "trente-quatre",
        "trente-cinq",
        "trente-six",
        "trente-sept",
        "trente-huit",
        "trente-neuf",
        "quarante",
        "quarante et un",
        "quarante-deux",
        "quarante-trois",
        "quarante-quatre",
        "quarante-cinq",
        "quarante-six",
        "quarante-sept",
        "quarante-huit",
        "quarante-neuf",
        "cinquante",
        "cinquante et un",
        "cinquante-deux",
        "cinquante-trois",
        "cinquante-quatre",
        "cinquante-cinq",
        "cinquante-six",
        "cinquante-sept",
        "cinquante-huit",
        "cinquante-neuf",
        "soixante",
        "soixante et un",
        "soixante-deux",
        "soixante-trois",
        "soixante-quatre",
        "soixante-cinq",
        "soixante-six",
        "soixante-sept",
        "soixante-huit",
        "soixante-neuf",
        "soixante-dix",
        "soixante-et-onze",
        "soixante-douze",
        "soixante-treize",
        "soixante-quatorze",
        "soixante-quinze",
        "soixante-seize",
        "soixante-dix-sept",
        "soixante-dix-huit",
        "soixante-dix-neuf",
        "quatre-vingts",
        "quatre-vingt-un",
        "quatre-vingt-deux",
        "quatre-vingt-trois",
        "quatre-vingt-quatre",
        "quatre-vingt-cinq",
        "quatre-vingt-six",
        "quatre-vingt-sept",
        "quatre-vingt-huit",
        "quatre-vingt-neuf",
        "quatre-vingt-dix",
        "quatre-vingt-onze",
        "quatre-vingt-douze",
        "quatre-vingt-treize",
        "quatre-vingt-quatorze",
        "quatre-vingt-quinze",
        "quatre-vingt-seize",
        "quatre-vingt-dix-sept",
        "quatre-vingt-dix-huit",
        "quatre-vingt-dix-neuf"
    ],
    'questions': {
        "Who": "Qui",
        "What": "Que/Quoi",
        "Where": "Où",
        "When": "Quand",
        "Why": "Pourquoi",
        "How": "Comment",
        "Which": "Quel",
        "How Many": "Combien",
    },
    'colours': {
        "Black": "Noir",
        "White": "Blanc",
        "Blue": "Bleu",
        "Brown": "Marron",
        "Green": "Vert",
        "Gray": "Gris",
        "Orange": "Orange",
        "Pink": "Rose",
        "Purple": "Violet",
        "Red": "Rouge",
        "Yellow": "Jaune"
    }, 
    'mois': {
        "January": "Janvier",
        "Febuary": "Février",
        "March": "Mars",
        "April": "Avril",
        "May": "Mai",
        "June": "Juin",
        "July": "Juillet",
        "August": "Août",
        "September": "Septembre",
        "October": "Octobre", 
        "November": "Novembre",
        "December": "Décembre"
    },
    'jours': {
        "Monday": "Lundi",
        "Tuesday": "Mardi",
        "Wednesday": "Mercredi",
        "Thursday": "Jeudi",
        "Friday": "Vendredi",
        "Saturday": "Samedi",
        "Sunday": "Dimanche"
    },
    'corps': {
        "Hair": "Cheveux",
        "Head": "Tête",
        "Eyes": "Yeux",
        "Ear": "Oreille",
        "Mouth": "Bouche",
        "Shoulder": "Épaule",
        "Arm": "Bras",
        "Hand": "Main",
        "Leg": "Jambe",
        "Foot": "Pied"
    }
}

export default significantList
