const verbList = [
    {
        "Verb": "Être",
        "Translation": "To Be",
        "Tense": "Present",
        "Je": "suis",
        "Tu": "es",
        "Il": "est",
        "Nous": "sommes",
        "Vous": "êtes",
        "Ils": "sont"
    },
    {
        "Verb": "Manger",
        "Translation": "To Eat",
        "Tense": "Present",
        "Je": "mange",
        "Tu": "manges",
        "Il": "mange",
        "Nous": "mangeons",
        "Vous": "mangez",
        "Ils": "mangent"
    },
    {
        "Verb": "Parler",
        "Translation": "To Speak",
        "Tense": "Present",
        "Je": "parle",
        "Tu": "parles",
        "Il": "parle",
        "Nous": "parlons",
        "Vous": "parlez",
        "Ils": "parlent"
    },
    {
        "Verb": "Habiter",
        "Translation": "To Live",
        "Tense": "Present",
        "Je": "habite",
        "Tu": "habites",
        "Il": "habite",
        "Nous": "habitons",
        "Vous": "habitez",
        "Ils": "habitent"
    },
    {
        "Verb": "Étudier",
        "Translation": "To Study",
        "Tense": "Present",
        "Je": "étudie",
        "Tu": "étudies",
        "Il": "étudie",
        "Nous": "étudions",
        "Vous": "étudiez",
        "Ils": "étudient"
    },
    {
        "Verb": "Travailler",
        "Translation": "To Work",
        "Tense": "Present",
        "Je": "travaille",
        "Tu": "travailles",
        "Il": "travaille",
        "Nous": "travaillons",
        "Vous": "travaillez",
        "Ils": "travaillent"
    },
    {
        "Verb": "Prendre",
        "Translation": "To Take",
        "Tense": "Present",
        "Je": "prends",
        "Tu": "prends",
        "Il": "prend",
        "Nous": "prenons",
        "Vous": "prenez",
        "Ils": "prennet"
    },
    {
        "Verb": "Avoir",
        "Translation": "To Have",
        "Tense": "Present",
        "Je": "ai",
        "Tu": "as",
        "Il": "a",
        "Nous": "avons",
        "Vous": "avez",
        "Ils": "ont"
    },
    {
        "Verb": "Venir",
        "Translation": "To Come",
        "Tense": "Present",
        "Je": "viens",
        "Tu": "viens",
        "Il": "vient",
        "Nous": "venons",
        "Vous": "venez",
        "Ils": "viennent"
    },
    {
        "Verb": "Vouloir",
        "Translation": "To Want",
        "Tense": "Present",
        "Je": "veux",
        "Tu": "veux",
        "Il": "veut",
        "Nous": "voulons",
        "Vous": "voulez",
        "Ils": "veulent"
    },
    {
        "Verb": "Aimer",
        "Translation": "To Love",
        "Tense": "Present",
        "Je": "aime",
        "Tu": "aimes",
        "Il": "aime",
        "Nous": "aimons",
        "Vous": "aimez",
        "Ils": "aiment"
    },
    {
        "Verb": "Lire",
        "Translation": "To Read",
        "Tense": "Present",
        "Je": "lis",
        "Tu": "lis",
        "Il": "lit",
        "Nous": "lisons",
        "Vous": "lisez",
        "Ils": "lisent"
    },
    {
        "Verb": "Aller",
        "Translation": "To Go",
        "Tense": "Present",
        "Je": "vais",
        "Tu": "vas",
        "Il": "va",
        "Nous": "allons",
        "Vous": "allez",
        "Ils": "vont"
    },
    {
        "Verb": "Voulour",
        "Translation": "To Want",
        "Tense": "Future",
        "Je": "voudrai",
        "Tu": "voudras",
        "Il": "voudra",
        "Nous": "voudrons",
        "Vous": "voudrez",
        "Ils": "voudront"
    },
    {
        "Verb": "Visiter",
        "Translation": "To Visit",
        "Tense": "Present",
        "Je": "visite",
        "Tu": "visites",
        "Il": "visite",
        "Nous": "visitons",
        "Vous": "visitez",
        "Ils": "visitent"
    },
    {
        "Verb": "Voyager",
        "Translation": "To Travel",
        "Tense": "Present",
        "Je": "voyage",
        "Tu": "voyages",
        "Il": "voyage",
        "Nous": "voyageons",
        "Vous": "voyagez",
        "Ils": "voyagent"
    },
    {
        "Verb": "Ouvrir",
        "Translation": "To Open",
        "Tense": "Present",
        "Je": "ouvre",
        "Tu": "ouvres",
        "Il": "ouvre",
        "Nous": "ouvrons",
        "Vous": "ouvrez",
        "Ils": "ouvrent"
    },
    {
        "Verb": "Écrire",
        "Translation": "To Write",
        "Tense": "Present",
        "Je": "écris",
        "Tu": "écris",
        "Il": "écrit",
        "Nous": "écrivons",
        "Vous": "écrivez",
        "Ils": "écrivent"
    },
    {
        "Verb": "Utiliser",
        "Translation": "To Use",
        "Tense": "Present",
        "Je": "utilise",
        "Tu": "utilises",
        "Il": "utilise",
        "Nous": "utilisons",
        "Vous": "utilisez",
        "Ils": "utilisent"
    },
    {
        "Verb": "Préparer",
        "Translation": "To Prepare",
        "Tense": "Present",
        "Je": "prépare",
        "Tu": "prépares",
        "Il": "prépare",
        "Nous": "préparons",
        "Vous": "préparez",
        "Ils": "préparent"
    },
    {
        "Verb": "Cuire",
        "Translation": "To Cook",
        "Tense": "Present",
        "Je": "cuis",
        "Tu": "cuis",
        "Il": "cuit",
        "Nous": "cuisons",
        "Vous": "cuisez",
        "Ils": "cuisent"
    },
    {
        "Verb": "Regarder",
        "Translation": "To Watch",
        "Tense": "Present",
        "Je": "regarde",
        "Tu": "regardes",
        "Il": "regarde",
        "Nous": "regardons",
        "Vous": "regardez",
        "Ils": "regardent"
    },
    {
        "Verb": "Jouer",
        "Translation": "To Play",
        "Tense": "Present",
        "Je": "joue",
        "Tu": "joues",
        "Il": "joue",
        "Nous": "jouons",
        "Vous": "jouez",
        "Ils": "jouent"
    },
    {
        "Verb": "Dormir",
        "Translation": "To Sleep",
        "Tense": "Present",
        "Je": "dors",
        "Tu": "dors",
        "Il": "dort",
        "Nous": "dormons",
        "Vous": "dormez",
        "Ils": "dorment"
    },
    {
        "Verb": "Écouter",
        "Translation": "To Listen",
        "Tense": "Present",
        "Je": "écoute",
        "Tu": "écoutes",
        "Il": "écoute",
        "Nous": "écoutons",
        "Vous": "écoutez",
        "Ils": "écoutent"
    },
    {
        "Verb": "Coûter",
        "Translation": "To Cook",
        "Tense": "Present",
        "Je": "coûte",
        "Tu": "coûtes",
        "Il": "coûte",
        "Nous": "coûtons",
        "Vous": "coûtez",
        "Ils": "coûtent"
    },
    {
        "Verb": "Acheter",
        "Translation": "To Buy",
        "Tense": "Present",
        "Je": "achète",
        "Tu": "achètes",
        "Il": "achète",
        "Nous": "achètons",
        "Vous": "achètez",
        "Ils": "achètent"
    },
    {
        "Verb": "Pouvour",
        "Translation": "To Be Able To",
        "Tense": "Present",
        "Je": "peux",
        "Tu": "peux",
        "Il": "peut",
        "Nous": "pouvons",
        "Vous": "pouvez",
        "Ils": "pouvent"
    },
    {
        "Verb": "Cuisiner",
        "Translation": "To Cook",
        "Tense": "Present",
        "Je": "cuisine",
        "Tu": "cuisines",
        "Il": "cuisine",
        "Nous": "cuisions",
        "Vous": "cuisinez",
        "Ils": "cuisinent"
    },
    {
        "Verb": "Devoir",
        "Translation": "To Have To",
        "Tense": "Present",
        "Je": "dois",
        "Tu": "dois",
        "Il": "doit",
        "Nous": "devons",
        "Vous": "devez",
        "Ils": "doivent"
    },
    {
        "Verb": "Marcher",
        "Translation": "To Walk",
        "Tense": "Present",
        "Je": "marche",
        "Tu": "marches",
        "Il": "marche",
        "Nous": "marchons",
        "Vous": "marchez",
        "Ils": "marchent"
    },
    {
        "Verb": "Tourner",
        "Translation": "To Turn",
        "Tense": "Present",
        "Je": "tourne",
        "Tu": "tournes",
        "Il": "tourne",
        "Nous": "tournons",
        "Vous": "tournez",
        "Ils": "tournent"
    },
    {
        "Verb": "Trouve",
        "Translation": "To Find",
        "Tense": "Present",
        "Je": "trouve",
        "Tu": "trouves",
        "Il": "trouve",
        "Nous": "trouvons",
        "Vous": "trouvez",
        "Ils": "trouvent"
    },
    {
        "Verb": "Danser",
        "Translation": "To Dance",
        "Tense": "Present",
        "Je": "danse",
        "Tu": "danses",
        "Il": "danse",
        "Nous": "dansons",
        "Vous": "dansez",
        "Ils": "dansent"
    },
    {
        "Verb": "Sortir",
        "Translation": "To Go Out",
        "Tense": "Present",
        "Je": "sors",
        "Tu": "sors",
        "Il": "sort",
        "Nous": "sortons",
        "Vous": "sortez",
        "Ils": "sortent"
    },
    {
        "Verb": "Rentrer",
        "Translation": "To Return",
        "Tense": "Present",
        "Je": "rentre",
        "Tu": "rentres",
        "Il": "rentre",
        "Nous": "rentrons",
        "Vous": "rentrez",
        "Ils": "rentrent"
    },
    {
        "Verb": "Boire",
        "Translation": "To Drink",
        "Tense": "Present",
        "Je": "bois",
        "Tu": "bois",
        "Il": "boit",
        "Nous": "buvons",
        "Vous": "buvez",
        "Ils": "boivent"
    },
    {
        "Verb": "Attendre",
        "Translation": "To Wait",
        "Tense": "Present",
        "Je": "attends",
        "Tu": "attends",
        "Il": "attend",
        "Nous": "attendons",
        "Vous": "attendez",
        "Ils": "attendent"
    },
    {
        "Verb": "Chanter",
        "Translation": "To Sing",
        "Tense": "Present",
        "Je": "chante",
        "Tu": "chantes",
        "Il": "chante",
        "Nous": "chantons",
        "Vous": "chantez",
        "Ils": "chantent"
    },
    {
        "Verb": "Nager",
        "Translation": "To Swim",
        "Tense": "Present",
        "Je": "nage",
        "Tu": "nages",
        "Il": "nage",
        "Nous": "nageons",
        "Vous": "nagez",
        "Ils": "nagent"
    },
    {
        "Verb": "Dessiner",
        "Translation": "To Draw",
        "Tense": "Present",
        "Je": "dessine",
        "Tu": "dessines",
        "Il": "dessine",
        "Nous": "dessinons",
        "Vous": "dessinez",
        "Ils": "dessinent"
    },
]

export default verbList